<script>
    import { Link } from "svelte-routing";
    import { onMount } from "svelte";
    import { fade } from "svelte/transition";

    let dinamicClass = "";
    let dinamicClassMain = "";
    let dinamicRotate = "";
    onMount(() => {
        setTimeout(() => {
            dinamicClass = "eye-open";
            setTimeout(() => {
                dinamicClassMain = "float-left";
                setTimeout(() => {
                    dinamicRotate = "rotate";
                }, 4000);
            }, 1500);
        }, 700);
    });
</script>

<style>
    main {
        display: flex;
        justify-content: flex-end;
        min-height: 100vh;
        height: auto;
        align-items: center;
        margin-left: 40px;
        overflow-x: hidden;
        position: relative;
    }
    .circle {
        width: 700px;
        height: 700px;
        border: 60px solid black;
        border-radius: 50%;
        display: flex;
        transform: translateX(0);
        transition: transform 3s;
        position: absolute;
        z-index: 0;
    }
    .circle.float-left {
        transform: translateX(-70%);
    }
    .circle.float-left.dinamicRotate {
        animation: rotate-hor-center 3s cubic-bezier(0.175, 0.885, 0.32, 1.275)
            both;
    }
    .circle-1 {
        width: calc(700px - 50%);
        height: calc(700px - 50%);
        border: 60px solid black;
        border-radius: 50%;
        margin: auto auto;
        display: inherit;
        transition: width 3s;
    }
    .circle-1.eye-open {
        width: 700px !important;
    }
    .circle-1.eye-open.float-left {
        animation: rotate-center 5s ease-in-out both;
    }
    .circle-2 {
        width: 100px;
        height: 100px;
        background-color: black;
        border-radius: 50%;
        margin: auto auto;
    }

    .layout-skill {
        width: 50%;
        background: black;
        height: 0%;
        transform: translateY(100%);
        float: right;
        transition: transform 3s;
    }
    .layout-skill.float-left {
        height: 100%;
        min-height: 100vh;
        transform: translateY(0%);
    }

    .layout-skill h2,
    .layout-skill p {
        display: none;
        transition: display 3s;
        z-index: 1;
        position: relative;
    }

    .layout-skill.float-left h2 {
        display: block;
        color: white;
        font-size: 40px;
        text-align: right;
        padding-right: 40px;
    }

    .layout-skill.float-left p {
        display: block;
        color: white;
        font-size: 22px;
        text-align: right;
        padding: 20px 40px 20px 40px;
    }
    .layout-skill.float-left p span {
        text-decoration: underline;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2021-5-6 23:11:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
    @keyframes rotate-center {
        0% {
            -webkit-transform: rotate(0);
            transform: rotate(0);
        }
        100% {
            -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
        }
    }
    @keyframes rotate-hor-center {
        0% {
            -webkit-transform: rotateX(0);
            transform: rotateX(0);
        }
        100% {
            -webkit-transform: rotateX(-360deg);
            transform: rotateX(-360deg);
        }
    }
</style>

<main>
    <div
        class="circle {dinamicClassMain} {dinamicRotate}"
        transition:fade={{ duration: 1500 }}>
        <div class="circle-1 {dinamicClass} {dinamicClassMain}">
            <div class="blink" />
            <div class="circle-2" />
        </div>
    </div>

    <div class="layout-skill {dinamicClassMain}">
        <h2>Skills</h2>

        <p>Si hablamos de lo técnico JS es el lenguaje.</p>

        <p>
            He trabajado con
            <span>React</span>
            y
            <span>React Native</span>, y
            <span>Angular</span>
            en sus versiones modernas (y las no tanto). Maquetación con
            <span>Bootstrap</span>
            y
            <span>Materialize</span>
            , como también en la construcción de
            <span>Web Components</span>
            con Atómico. Esta web fue creada con
            <span>Svelte</span>
            . Entiendo y manejo de Backend, Devops y User Experience lo
            suficiente para cuestionar y/o aportar.
        </p>

        <p>Y las otras skills ...</p>

        <p>
            Comunicación, tomar responsabilidad y trabajar en equipo. Tengo una
            personalidad muy activa y entusiasta. Busco siempre dar más,
            llevarme al límite y vivir en esa zona
        </p>

        <Link to="/aboutMe">¿Quien soy ...?</Link>
    </div>
</main>
